# Generated by Django 5.2.8 on 2025-11-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_rename_autor_libro_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.CharField(default='Desconocido', max_length=150),
            preserve_default=False,
        ),
    ]
