# Generated by Django 5.2.8 on 2025-11-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_alter_libro_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='image',
            field=models.ImageField(null=True, upload_to='imagenes_libros'),
        ),
    ]
