# Generated by Django 5.2.8 on 2025-11-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_libro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='image',
            field=models.ImageField(null=True, upload_to='imagenes_libros/'),
        ),
    ]
