# Generated by Django 5.2.8 on 2025-11-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_alter_libro_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='image',
        ),
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(default=1, upload_to='libros/'),
            preserve_default=False,
        ),
    ]
